trigger:
- master

pr:
  autoCancel: true
  branches:
    include:
    - master

jobs:
- job: WhatsNewUpdate
  displayName: '1. What s New Update'
  pool:
    vmImage: 'Ubuntu-16.04'
    demands: npm
  steps:
  - script: 'npm install'
    displayName: 'Npm install'
  - script: 'npm run whatsNew'
    displayName: 'Whats new'
    env:
      AZURE_PULLREQUESTID: $(System.PullRequest.PullRequestId)
      NPM_USERNAME: $(babylon.npm.username)

- job: TscBuild
  displayName: '2. Tsc Build'
  pool:
    vmImage: 'Ubuntu-16.04'
    demands: npm
  steps:
  - script: 'npm install'
    displayName: 'Npm install'
  - script: 'npm run build'
    displayName: 'Tsc Build'